# Generated by Django 3.2.18 on 2023-07-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FotosChicaPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpropiedad', models.IntegerField(db_column='IdPropiedad')),
                ('foto', models.TextField(db_column='Foto')),
            ],
            options={
                'db_table': 'fotos_chica_propiedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FotosMedianaPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpropiedad', models.IntegerField(db_column='IdPropiedad')),
                ('foto', models.TextField(db_column='Foto')),
            ],
            options={
                'db_table': 'fotos_mediana_propiedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FotosPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpropiedad', models.IntegerField(db_column='IdPropiedad')),
                ('foto', models.TextField(db_column='Foto')),
            ],
            options={
                'db_table': 'fotos_propiedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_externo', models.CharField(max_length=45)),
                ('codigo_interno', models.CharField(max_length=45)),
                ('tipo_operacion', models.SmallIntegerField()),
                ('tipo_propiedad', models.SmallIntegerField()),
                ('tipo_provincia', models.SmallIntegerField()),
                ('tipo_barrio', models.SmallIntegerField()),
                ('tipo_ambiente', models.SmallIntegerField()),
                ('valor', models.IntegerField()),
                ('descripcion', models.TextField(db_collation='utf8_swedish_ci')),
                ('calle', models.CharField(max_length=45)),
                ('altura', models.SmallIntegerField()),
                ('piso', models.CharField(max_length=3)),
                ('depto', models.CharField(max_length=3)),
                ('torre', models.CharField(max_length=10)),
                ('fecha_alta', models.DateTimeField()),
                ('moneda', models.CharField(max_length=10)),
                ('reservado', models.IntegerField()),
            ],
            options={
                'db_table': 'propiedades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAmbientes',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_ambientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoBarrio',
            fields=[
                ('id_provincia', models.PositiveIntegerField()),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_barrio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_operacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_propiedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProvincia',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_provincia',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
    ]
