# Generated by Django 3.2.18 on 2023-07-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20230720_2018'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='administracion_categoria',
        ),
    ]
