# Generated by Django 3.2.18 on 2023-07-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_categoria_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoprovincia',
            options={},
        ),
    ]
