# Generated by Django 3.2.18 on 2023-07-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_tipoprovincia_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipoprovincia',
            table=None,
        ),
    ]
