# Generated by Django 3.2.18 on 2023-07-30 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_tipoprovincia_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='https://purplecow.com.ar/images/propiedades/')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='administracion.propiedades')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='FotosChicaPropiedad',
        ),
        migrations.DeleteModel(
            name='FotosMedianaPropiedad',
        ),
        migrations.DeleteModel(
            name='FotosPropiedad',
        ),
        migrations.AlterModelOptions(
            name='tipoprovincia',
            options={'managed': False},
        ),
    ]
